name: Docs to PDF
# This workflow is triggered on published releases
on:
  release:
    types: [published]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Convert GitHub markdown (gfm) to PDF
      - uses: docker://pandoc/latex:3.2.0
        with:
          args: >-  # allows you to break string into multiple lines
            -f gfm
            -t pdf
            --output=pdfs/wallet-safety-guide-and-checklist.pdf
            docs/wallet-safety-guide-and-checklist.md
          
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs

